version: '3.4'

services:

  mongo2:
    #build: ./Mongo/
    image: mongo:3.6
    restart: always
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123